Peter Grandstaff: Intro of conference co-chair
djangocon/2023.djangocon.us pull request #119
Opened 2023-06-23 13:55 UTC by jcjudkins

- Added interview post for Peter Grandstaff (Intro as conference co-chair)

2023-06-23 15:03 UTC, emullaney commented on _posts/2023-06-26-peter-grandstaff-introduction.md
> +This week I had the pleasure of chatting with one of the DjangoCon US 2023 Conference Co-Chairs, Peter Grandstaff, about her role as a conference chair and his experience with Django.
about "his" role 

(probably a copy paste error from a previous post?)

2023-06-23 15:07 UTC, emullaney commented on _posts/2023-06-26-peter-grandstaff-introduction.md
> +### We organizers would like to thank Peter for her leadership and work with the planning of DjangoCon US 2023!
s/her/his

2023-06-23 15:08 UTC, emullaney requested changes
Looks really good! Caught two gender errors (probably copy pasta) and commented.

Also, I love this quote from Peter and it would be a fun pull quote for sharing on socials!
>Just, don't write it in PHP without a framework like I did. Use a framework. Use Django

2023-06-23 15:14 UTC, drewbrew approved these changes

2023-06-23 15:14 UTC, drewbrew commented on _posts/2023-06-26-peter-grandstaff-introduction.md
> +>It was in 2020 when I got to work with [Dawn Wages](http://dawnwages.info/) that I first heard some really wonderful accounts of DjangoCon US and how amazing the Django community was. I attended onl
```suggestion
>It was in 2020 when I got to work with DCUS Sponsorship co-chair [Dawn Wages](http://dawnwages.info/) that I first heard some really wonderful accounts of DjangoCon US and how amazing the Django community was. I attended online in 2021 and 2022 and was pretty impressed.
```

2023-06-23 15:14 UTC, drewbrew commented on _posts/2023-06-26-peter-grandstaff-introduction.md
> +> Peter: "Prior to the organizing kickoff for 2023 I'd already taken on some level of leadership by hammering out all the venue and hotel contracts here in Durham. It kind of felt like a natural cont
```suggestion
> Peter: "Prior to the organizing kickoff for 2023 I'd already taken on some level of leadership by hammering out all the venue and hotel contracts here in Durham. It kind of felt like a natural continuation of what I'd been doing. I'm a DjangoCon US newbie, so I was definitely reluctant to take a leadership role like that. Once I saw how many passionate and engaged volunteers we had showing up to the organizer meetings I felt confident that the Chair role was something I could manage. At least, I could manage it with a good co-chair as backup. Thankfully, the very talented Adrienne Franke [the other co-chair] agreed to take on that role."
```

2023-06-23 15:14 UTC, drewbrew commented on _posts/2023-06-26-peter-grandstaff-introduction.md
> +> Peter: "The DjangoCon US organizers slack is a great place to find me, or you can find more info and contact information on the Two Rock Software website, [Two Rock](https://tworock.io)"
```suggestion
> Peter: "The DjangoCon US organizers Slack is a great place to find me, or you can find more info and contact information on the Two Rock Software website, [Two Rock](https://tworock.io)"
```

2023-06-23 15:14 UTC, drewbrew commented on _posts/2023-06-26-peter-grandstaff-introduction.md
> +> Peter: "I think the best thing a new developer can do is to complete an entire project. Ideally, you'd find something you get paid to build, but sometimes it has to be a passion project of your own
As someone who ported a homegrown lamp stack to Django, I feel your pain

2023-06-23 19:11 UTC, PeterGrand commented
I don't really know what's normal here, but I've been referring to myself as Chair and Adrienne as Co-Chair, which in my head has been sort like President and Vice President. Happy to go with whatever nomenclature is normal for these, though.

2023-06-25 16:04 UTC, jcjudkins commented on _posts/2023-06-26-peter-grandstaff-introduction.md
> +### We organizers would like to thank Peter for her leadership and work with the planning of DjangoCon US 2023!
🤦

2023-06-25 16:04 UTC, jcjudkins commented on _posts/2023-06-26-peter-grandstaff-introduction.md
> +This week I had the pleasure of chatting with one of the DjangoCon US 2023 Conference Co-Chairs, Peter Grandstaff, about her role as a conference chair and his experience with Django.
Indeed!

2023-06-25 16:09 UTC, jcjudkins commented
> I don't really know what's normal here, but I've been referring to myself as Chair and Adrienne as Co-Chair, which in my head has been sort like President and Vice President. Happy to go with whatever nomenclature is normal for these, though.

I did in fact know this! And forgot to update!

2023-06-25 16:15 UTC, drewbrew approved these changes

2023-06-26 14:30 UTC, merged