Julia Solorzano content updates
djangocon/2023.djangocon.us pull request #221
Opened 2023-10-02 00:51 UTC by juliaelman

Updating some of my speaker content - thank you!

2023-10-05 14:41 UTC, sodevious approved these changes

2023-10-05 14:43 UTC, sodevious requested changes
`Julia Solórzano is the Security Experience Supervisor based in Durham, NC` 

This may be a typo the way it's written with `the`

2023-10-05 14:44 UTC, drewbrew commented on _presenters/julia-solorzano.md
> +Julia Solórzano is the Security Experience Supervisor is based in Durham, NC. She leads security, user experience and engineering teams, and coaches people to help them reach their full potential to
It still reads as "Outside of Login.gov, her most recent work includes Login.gov." 

@juliaelman do you want to rephrase this?

2023-10-05 14:50 UTC, drewbrew commented
@sodevious It looks like @tim-schilling already fixed those wording issues. This one should be good to go after I fixed the merge conflicts.

2023-10-05 14:51 UTC, drewbrew approved these changes

2023-10-10 19:09 UTC, jefftriplett approved these changes

2023-10-10 19:10 UTC, merged

2023-10-10 19:12 UTC, jefftriplett commented
@juliaelman thank you! 

We can follow up with a new PR if something needs to be corrected.